### ISSUE TITLE
seems to ignore symbol key properties

### ISSUE THREAD

**Issue by mightyiam** [Xotic750/deep-equal-x#8]
Just like https://github.com/lodash/lodash/issues/2840.

**Comment by Xotic750** [comment]
I don't believe that at the time of writing this code that the deep-equal specification had any support for symbols. I haven't looked at the specification recently or checked if the most recent versions of nodejs support it?

**Comment by mightyiam** [comment]
You're correct. This adheres to node's assert. Thanks.
